name: particle_demo
dependencies:
  - python>=3.7
  # Setting recent versions to make the conda solve faster
  - numpy>=1.16
  - pandas>=0.24
  - attrs>=19.0
  - pip>=9.0
  - jupyterlab>=0.35
  - pip:
    - hepunits
    - tabulate
    - RISE
