name: particle_demo
channels:
  - conda-forge
dependencies:
  - python>=3.7
  # Setting recent versions to make the conda solve faster
  - numpy>=1.16
  - pandas>=0.24
  - attrs>=19.0
  - pip>=10.0
  - jupyterlab>=1.0
  - tabulate
  - RISE
  - pip:
    - .
