name: particle_demo
channels:
  - conda-forge
dependencies:
  - python>=3.8
  # Setting recent versions to make the conda solve faster
  - numpy>=1.16
  - pandas>=1
  - attrs>=19
  - jupyterlab>=4
  - tabulate
  - pip:
    - .
