#!/usr/bin/env python
# Copyright (c) 2018-2026, Eduardo Rodrigues and Henry Schreiner.
#
# Distributed under the 3-clause BSD license, see accompanying file LICENSE
# or https://github.com/scikit-hep/particle for details.
"""This script generates the PDGID<->RapidSim name mapping using the particles.dat file from the RapidSim repository."""

from __future__ import annotations

import csv
import datetime as dt

import requests


def download_table(
    url="https://raw.githubusercontent.com/gcowan/RapidSim/refs/heads/master/config/particles.dat",
):
    """Download RapidSim particles.dat file from GitHub repository."""
    r = requests.get(url)
    r.raise_for_status()

    lines = r.text.split("\n")

    # Skip header line and parse each row
    # Format: ID particle_name antiparticle_name mass width charge spin shape ctau
    entries = []
    for line in lines[1:]:  # Skip header
        parts = line.split()
        if len(parts) < 3:
            continue
        entries.append(parts)

    return entries


def main():
    date = dt.datetime.today().strftime("%Y-%m-%d")
    table = download_table()

    # Build mapping: particle and antiparticle entries
    rapidsim_names = {}
    for pdgid_str, part_name, anti_name, *_ in table:
        pdgid = int(pdgid_str)
        rapidsim_names[pdgid] = part_name
        if anti_name != "---":
            rapidsim_names[-pdgid] = anti_name

    with open("src/particle/rapidsim/data/pdgid_to_rapidsimname.csv", "w") as out_csv:
        out_csv.write(
            f"# (c) Scikit-HEP project - Particle package data file - pdgid_to_rapidsimname.csv - {date}\n"
        )
        out_csv.write(
            "# Auto generated by 'admin/dump_pdgid_to_rapidsimname.py'\n"
        )
        writer = csv.DictWriter(
            out_csv, fieldnames=("PDGID", "STR"), lineterminator="\n"
        )
        writer.writeheader()

        for pid, name in sorted(
            rapidsim_names.items(), key=lambda x: (abs(int(x[0])), -int(x[0]))
        ):
            writer.writerow({"PDGID": pid, "STR": name})


if __name__ == "__main__":
    main()
